# Site
name: "Cybernetic Site"
title: "Enter the Cybernetic Site"
description: "Electronics, Space, Hardware, Code, AI, Reviews and Cyber Wares!"
logo: 'assets/images/cyber-logo-dark.svg'
favicon: 'assets/images/cyber-icon.svg'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://cybernetic.site'
include: ["_pages"]
permalink: /:title/
email: info@cybernetic.site

# Authors
authors:
  vulcan:
    name: Vulcan Ignis
    display_name: Vulcan
    avatar: 'assets/images/cyber-icon.svg'
    email: vulcan@cybernetic.site
    web: https://cybernetic.site
    twitter: https://x.com/vulcanignis
    description: "Cybernetic Alien Cat Father"
  cyberteam:
    name: Cybernetic Team
    display_name: CT    
    avatar: 'assets/images/cyber-icon.svg'
    email: info@cybernetic.site
    web: https://cybernetic.site
    twitter: https://x.com/cyberneticware
    description: "We manage the cool merch here..."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-mermaid

# Mermaid
mermaid:
  src: 'assets/js/mermaid.min.js'

# Archives
#jekyll-archives:
#  enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/category/:name/'

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
  category: '/category/:name/'
  

# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

excerpt_separator: .



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
